version: '3'

networks:
    angular:

services:
    angular:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: angular
        ports:
            - "4200:80"
        networks: 
            - angular